# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sort-MonsterSort
version:      0.01
version_from: lib/Sort/MonsterSort.pm
installdirs:  site
requires:
    File::Temp:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
